[build] check if `$(JAVA_HOME_21_X64)` exists instead of agent name
Builds on the `main` branch fail with:

    ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/microsoft-21.jdk/Contents/Home

The current code is checking the `$(Agent.Name)`, but it should just check if the directory exists.